// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/[collection]/[[...params]]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/[collection]/[[...params]]">> = Specific
  const handler = {} as typeof import("../../app/api/[collection]/[[...params]]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/admin/[adminId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/[adminId]">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/admin/[adminId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/overview">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/faculty/[facultyId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/faculty/[facultyId]">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/faculty/[facultyId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/student/[studentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/student/[studentId]">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/student/[studentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/seed-activities/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-activities">> = Specific
  const handler = {} as typeof import("../../app/api/dev/seed-activities/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/seed-mongodb/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-mongodb">> = Specific
  const handler = {} as typeof import("../../app/api/dev/seed-mongodb/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dev/seed-students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dev/seed-students">> = Specific
  const handler = {} as typeof import("../../app/api/dev/seed-students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enrollments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enrollments">> = Specific
  const handler = {} as typeof import("../../app/api/enrollments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/[notificationId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/[notificationId]">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/[notificationId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/student-documents/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/student-documents/upload">> = Specific
  const handler = {} as typeof import("../../app/api/student-documents/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/uploads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/uploads">> = Specific
  const handler = {} as typeof import("../../app/api/uploads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
