var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12ah0kl._.js")
R.c("server/chunks/ssr/03fs_next_dist_esm_build_templates_app-page_0kdnc0y.js")
R.c("server/chunks/ssr/[root-of-the-server]__0lm~325._.js")
R.c("server/chunks/ssr/[root-of-the-server]__13cuasf._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x8kuk0._.js")
R.c("server/chunks/ssr/03fs_next_dist_client_components_0t9jt7q._.js")
R.c("server/chunks/ssr/03fs_next_dist_client_components_builtin_forbidden_0mw8ug9.js")
R.c("server/chunks/ssr/03fs_next_dist_client_components_builtin_unauthorized_007ljvo.js")
R.c("server/chunks/ssr/_next-internal_server_app__not-found_page_actions_0eq97pa.js")
R.m(83927)
module.exports=R.m(83927).exports
